### PR TITLE
Optimized Popup and Modal loading

### PR DESCRIPTION
**Pull request by ajayparsana**
Optimized Popup and Modal loading
Added Optimization
Closed Popup on Today Button Clicked
Disabled Prv & Next Month Button if from & to is provided
InputDate is selected if passed.
Please contact ajay.parsana@gmail.com for any clarification

Signed-off-by: Ajay Parsana <ajay.parsana@gmail.com>

### CODE REVIEW

**Comment by rajeshwarpatlolla** [comment]
Thank you so much @ajayparsana. I will take a look at this PR.

**Comment by ajayparsana** [comment]
No issue. I felt good to contribute to this.

**Comment by rajeshwarpatlolla** [comment]
Could you please take a look at the conflicts and update the PR.

**Comment by ajayparsana** [comment]
Ok. I will check.

**Pull request closed without merging**
