### PR TITLE
Defualt styles from ionic

### PR DESCRIPTION
**Pull request by sebrojas14**
I think is better to use default styles of ionic instead of alot of custom css. Now is using positive color, so thta updates accourding to apps defaults

image

### CODE REVIEW

**Comment by sebrojas14** [comment]
Still incomplete

**Comment by olmesm** [comment]
@sebrojas14 did you manage to complete this?

**Comment by sebrojas14** [comment]
Yes, https://github.com/Hobbule/ionic-datepicker

**Comment by sebrojas14** [comment]
And for the timepicker also https://github.com/Hobbule/ionic-timepicker @olmesm

**Pull request closed without merging**
