### PR TITLE
Added inline calendar supporting events

### PR DESCRIPTION
**Pull request by rjcarneiro**
Create a new directive for <date-picker>:

- Supports events
- Inline calendar

### CODE REVIEW

**Comment by Dammmien** [comment]
The ionic-datepicker.directive.js is a great feature, there is no way to do this currently ?
It is essential to be able to use the datepicker without displaying it in a modal.

**Comment by rajeshwarpatlolla** [comment]
Is it like using the same code in the directive?

**Comment by rjcarneiro** [comment]
Hi @Dammmien and @rajeshwarpatlolla,

I develop the directive in order to use the calendar in a ionic-view, inline, without popup or modal.

capture

**Comment by Dammmien** [comment]
Yes, that's what i'm looking for but I think it's a lot of code for a datepicker that already exists.
No way to implement this more simply ?
In ionic, if not a tip for a home made implementation may interest me.

**Comment by rjcarneiro** [comment]
@Dammmien possible, there's a simple way... I just grab the code for the provider and adapted it to the directive. I think it's independent module that's why the code is the same...

...Still, feel free to improve this code ;)

**Pull request closed without merging**
