### PR TITLE
Today routine adjustment

### PR DESCRIPTION
**Pull request by raphaelduartepinheiro**
#29

### CODE REVIEW

**Comment by rajeshwarpatlolla** [comment]
There are few other changes also. So i implemented the functionality for which you made a pull request. I released a new version v0.4.0. Please use the latest version.

**Comment by raphaelduartepinheiro** [comment]
Sorry @rajeshwarpatlolla, but you always say it in the pull requests. Since this project is open source, it is polite you to accept the PR. This way you discourages comunity contribution.

**Comment by rajeshwarpatlolla** [comment]
You misunderstood me. I said there are few other changes i need to do. Even i could have merged your PR. But i had to add few other lines along with your code. Even after merging your request, there would few other things i need to do. Any how i am adding your code, and you are the source for that code snippet. If you have didn't made this PR, i even didn't get this idea. So you are always one contributor for this project. 

But still i can understand your concern. From now on i will merge PR, and if there needs to be any changes, i will add again and make a new release. Sorry for your concern.

**Comment by raphaelduartepinheiro** [comment]
:) Glad you understood.

**Comment by rajeshwarpatlolla** [comment]
Thanks for your PR and concern. Remember you are always one of the contributor for this project.

**Pull request closed without merging**
