### PR TITLE
Added feature for disabling specific dates

### PR DESCRIPTION
**Pull request by campsjos**
`disableddates` optional attribute for `ionic-datepicker` directive disables the days in the calendar specified in a Date objects array.

Example of use:

```javascript
//controllers.js
$scope.disabledDates = [
      new Date(2015,7,10), //months are 0-based, this is August, 10th!
      new Date('Wednesday, August 12, 2015'), //Works with any valid Date formats like long format
      new Date("08-14-2015"), //Short format
      new Date(1439676000000) //UNIX format
    ];
```
```html
<ionic-datepicker 
    idate="currentDate" 
    disablepreviousdates="true" 
    disableddates="disabledDates">
    <button class="button button-block button-positive"> 
        {{ currentDate | date:'dd - MMMM - yyyy' }}
    </button>
</ionic-datepicker>
```

### CODE REVIEW

**Comment by rajeshwarpatlolla** [comment]
Thanks for you PR. I have merged one of your PR. I tried to merge this too, but getting an error.

To git@github-personal:rajeshwarpatlolla/ionic-datepicker.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'git@github-personal:rajeshwarpatlolla/ionic-datepicker.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by campsjos** [comment]
I've got the same error when tried to merge my 2 commits in my fork marter branch... I do not know really how solve it...

**Comment by rajeshwarpatlolla** [comment]
Ok, i merged your other PR, i will add your code of this PR in to my next release and then i will close this PR. Is this ok for you?

**Comment by campsjos** [comment]
Yes, of course!

**Comment by rajeshwarpatlolla** [comment]
ok, Thanks for your PR :-)

**Comment by rajeshwarpatlolla** [comment]
Merged in to new version v0.5.0. Thanks again for your PR.

**Pull request closed without merging**
