### PR TITLE
Return a function that allows one to close the picker programmatically

### PR DESCRIPTION
**Pull request by sebastien-p**

### CODE REVIEW

**Comment by sebastien-p** [comment]
Please merge this, it even includes a regression fix. The only conflict here is the built version, easy merging ahead :)

**Comment by koreem** [comment]
Nice solution, exactly what I was looking for, thanks!

**Comment by sebastien-p** [comment]
Your'e welcome, hopefully this will be merged at some point.

**Comment by rajeshwarpatlolla** [comment]
Could you please resolve the conflicts and update the PR?

**Pull request closed without merging**
